name: Deploy PROD EMBED

on:
  workflow_call:

jobs:
  deploy_embed_eu:
    uses: ./.github/workflows/reusable-embed-deploy.yml
    with:
      environment: Production
      widget_url: https://eu.widget.novu.co
      netlify_deploy_message: Production deployment
      netlify_alias: prod
      netlify_gh_env: Production
      netlify_site_id: 0c830b50-df83-480b-ba36-a7f3176efcc8
    secrets: inherit

  deploy_embed_us:
    uses: ./.github/workflows/reusable-embed-deploy.yml
    with:
      environment: Production
      widget_url: https://widget.novu.co
      netlify_deploy_message: Production deployment
      netlify_alias: prod
      netlify_gh_env: Production
      netlify_site_id: 0689c015-fca0-4940-a26d-3e33f561bc48
    secrets: inherit

