name: Setup QEMU

description: Configures QEMU for cross-platform builds.

runs:
  using: composite
  steps:
    - uses: crazy-max/ghaction-setup-docker@v2
      with:
        version: v24.0.6
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: 'image=moby/buildkit:v0.13.1'
